export const eventCategories = {
  "Holidays and Celebrations": [
    "Thanksgiving",
    "New Year Celebrations",
    "Halloween",
    "Valentine",
    "Christmas",
    "Easter",
    "Wedding Ceremony",
    "Birthday Party",
  ],
  "Festivals Events": [
    "Food Festival",
    "Cosplay Festival",
    "Sports Festival",
    "Street Food Festival",
    "Light Festival",
    "Firework Festival",
  ],
  "Public Events": [
    "Marathon",
    "Concert",
    "Book Fair",
    "Pool Party",
    "Movie Night",
    "Grand Opening",
    "Car Show",
    "Public Event",
    "Art & Exhibits",
  ],
  "Social Gatherings and Leisure Activities": [
    "Daily Life Snapshot",
    "Karaoke",
    "Meeting",
    "Conversation",
    "Sports Activity",
    "Dating",
    "Friend Meet-Up",
    "Safari",
    "Shopping",
    "Prom Night",
  ],
  "Travel Events": [
    "Camping Weekend",
    "Road Trip",
    "Flight",
    "Traveling",
    "Stargazing Night",
  ],
  "Educational and Professional Events": [
    "Conference",
    "Lecture",
    "School Day",
  ],
  "Seasonal and Nature": [
    "Morning",
    "Evening",
    "Spring",
    "Summer",
    "Autumn",
    "Winter",
    "Sunrise and Sunset",
  ],
};
